### ISSUE TITLE
Create AAU title page

### ISSUE THREAD

**Issue by audio-engineer** [audio-engineer/aau-p2-article#19]
Relevant parts of [AAU LaTeX report template](https://www.overleaf.com/latex/templates/aalborg-university-aau-report-template-improved-version/vccnpjjqpdnf) should be imported/added to the current LaTeX project. This should be done as soon and as early in the writing process as possible in order to minimize compatibility issues later on.

**Comment by Danar435** [comment]
Are we not going to merge the report with the title page like last time?

**Comment by audio-engineer** [comment]
@Danar435 We did it last time because we were running out of time, and migrating the whole project to the template would have been a disaster. This time, we can just import the title page directly into the project, and leave the rest as it is. i will take care of it
