### ISSUE TITLE
Move web app sketch to Figma project

### ISSUE THREAD

**Issue by audio-engineer** [audio-engineer/aau-p2-article#2]
The current web app sketch should be redrawn in Figma

**Comment by audio-engineer** [comment]
@Danar435 What's the status here? Can it be closed?

**Comment by Danar435** [comment]
There are still a few areas I want to touch on, probably tomorrow

**Comment by Danar435** [comment]
It has been done! Link to Figma:

https://www.figma.com/file/lJuRNhAIiFWZqCDvz31PTr/Chess-design?type=design&node-id=0%3A1&mode=design&t=zfdosNiHHMcE2MsR-1
